### ISSUE TITLE
Language is Dutch for some reason?

### ISSUE THREAD

**Issue by evertvorster** [michjans/routegen#3]
Hi there!

Just found this software, and made an Arch AUR package for it. 

This package builds from source after having checked it out from the master branch on Github. 

This software looks like it does exactly what I would like it to do for one of my video projects. 

Unfortunately, the language for everything in the program seems to be in Dutch. Is there a compile switch I can set to make it English?

Fortunately I can read a little Dutch, so it is not such a huge obstacle for me, but I do want to make the package more acceptable for most people, who may not be able to read Dutch.

Kind regards,
-Evert-

**Comment by michjans** [comment]
I am at the moment working on adding translations and Dutch is one of them. For now I have reset the default language back to EN on the master branch. However, have to add the warning that the master branch can be unstable because it's used for active development. Better use a released version if you want to use a stable release.
